### PR TITLE
Update to work with latest Wildfly

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Does this mean it only works with WF 12, or does it still work with WF 11?

**Comment by stuartwdouglas** [comment]
It will still work with earlier versions

**Comment by stuartwdouglas** [comment]
As part of the dual EE7/EE8 support we had to support multiple versions of the same artifact, so some artifacts have their version hard coded in module.xml. This change adds support for that.

**Comment by bobmcwhirter** [comment]
Writing a DUP/Subsystem from the WildFly Swarm POV is not easy or fun.

Is there some DMR we can use to install a ThreadSetupAction to install a magical/slightly-different TCCL?

**Comment by kenfinnigan** [comment]
test this please

**Review by kenfinnigan — APPROVED** [review]

**Pull request merged**
