### PR TITLE
SWARM-1267: Fix Maven coordinates with classifier in ModuleFiller

### PR DESCRIPTION
**Pull request by famod**
Motivation
----------
Building wildfly-swarm logs scary exceptions for some executions of the plugin because Aether cannot find certain artifacts requested by ModuleFiller.
The affected artifact coordinates are malformed and do not adhere to the contract that is defined by Aether's DefaultArtifact class.

Modifications
-------------
Instead of "reducing" the artifact entries from *-feature-pack.xml to module name strings (which represent malformed coordinates when a classifier is involved), build DefaultArtifact instances early on and convert them to module names on demand.

Result
------
ModuleFiller now properly handles artifacts with classifiers.

### CODE REVIEW

**Comment by famod** [comment]
Notes:
- I have updated my local `master` branch of `wildfly-swarm` to 53-SNAPSHOT (including this change) and ran `mvn clean install`. The problem has vanished and all tests are passing.
- The parsing of `artifact` entries from `*-feature-pack.xml` seems pretty fragile to me as it depends on the order of XML attributes which can theoretically change without notice.
- Once (if) this PR is merged, who updates the version in `wildfly-swarm`?

**Comment by bobmcwhirter** [comment]
okay to test

**Comment by bobmcwhirter** [comment]
@famod If we merge this, once it's released (whenever we like) we bump the main repository to use it.

**Review by bobmcwhirter — APPROVED** [review]

**Comment by bobmcwhirter** [comment]
I'm testing this locally prior to merging.

**Pull request merged**
