### PR TITLE
SWARM-680: Update to Jandex 2.0.3.Final

### PR DESCRIPTION
**Pull request by gastaldi**
- [X] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document? 
- [X] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message? 
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue? 
- [X] Have you built the project locally prior to submission with `mvn clean install`?

---
## Motivation

Jandex 2.0.3.Final was enhanced to distinguish inner and static nested classes.
## Modifications

The Jandex version was upgraded in pom.xml
## Result

Jandex 2.0.3.Final is now used

### CODE REVIEW

**Comment by kenfinnigan** [comment]
bit late now, but do we even need jandex processing of fraction classes?

Previously it was added as we were service loading classes and searching by name, etc, but we don't do that anymore

**Comment by heiko-braun** [comment]
IIRC it's still used for deployment meta data

**Comment by kenfinnigan** [comment]
Right, but that doesn't rely on jandex from the fractions themselves, unless I'm mistaken?

**Comment by heiko-braun** [comment]
yes, that's correct

**Pull request merged**
