### PR TITLE
SWARM-1515: Fix RepositoryBuilderMojo.

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Review by heiko-braun — APPROVED** [review]
AFAIK this looks good

**Comment by heiko-braun** [comment]
@mkouba I assume, once in place, you also need another release of the plugin?

**Comment by heiko-braun** [comment]
ah, ignore my last comment :) it's part of core

**Comment by mkouba** [comment]
Yep, the release and upgrade in https://github.com/wildfly-swarm-prod/wildfly-swarm is necessary.

**Comment by heiko-braun** [comment]
@kenfinnigan I'll leave that to you

**Review by kenfinnigan — APPROVED** [review]

**Pull request merged**
